version: "3.1"
services:

  web:
    image: yiisoftware/yii2-php:7.3-apache
    restart: always
    volumes:
      - ./yii:/app
      - ./data/conf:/etc/apache2/sites-available
      - ./data/logs:/var/log/apache2
    env_file:
      - ./secret/dev.env
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mariadb
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - ./secret/dev.env
    ports:
      - "8890:3306"

networks:
  default:
    external:
      name: amp-yii